-- Criação da tabela de mensagens para BestStag v8.0 MVP
CREATE TABLE IF NOT EXISTS public.mensagens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT REFERENCES public.usuarios(id) ON DELETE CASCADE,
  role        TEXT NOT NULL CHECK (role IN ('user','assistant')),
  content     TEXT NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mensagens_user_id ON public.mensagens(user_id);
CREATE INDEX IF NOT EXISTS idx_mensagens_role ON public.mensagens(role);

ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Mensagens_Select_Public" ON public.mensagens
FOR SELECT TO public USING (true);

CREATE POLICY "Mensagens_Insert_Public" ON public.mensagens
FOR INSERT TO public WITH CHECK (true);
