-- Criação da tabela de usuários para BestStag v8.0 MVP
CREATE TABLE IF NOT EXISTS public.usuarios (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome      TEXT,
  email     TEXT,
  telefone  TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_usuarios_telefone ON public.usuarios(telefone);

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuarios_Insert_Public" ON public.usuarios
FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Usuarios_Select_Public" ON public.usuarios
FOR SELECT TO public USING (true);
